name: Build, Push and Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image with the "latest" tag
      - name: Build Docker image
        run: |
          docker build -t osegbu/pychat-user-service:${{ github.sha }} .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push osegbu/pychat-user-service:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 5: Deploy to k3s using SSH
      - name: Deploy to k3s
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > my-key.pem
          chmod 600 my-key.pem
          ssh -o StrictHostKeyChecking=no -i my-key.pem ec2-user@ec2-100-26-193-126.compute-1.amazonaws.com "
            sudo sed -i 's|image: .*|image: osegbu/pychat-user-service:${{ github.sha }}|' ~/user-service-deployment.yaml;
            sudo kubectl apply -f ~/user-service-deployment.yaml
          "
          rm my-key.pem
